name: gitleaks-action-HEAD

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: gitleaks-action-HEAD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          
      - name: Download required files
        run : |
          content=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/scriptkidakash81/example/.github/gitleaks.toml > gitleaks.toml
          content=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/scriptkidakash81/example/action.yml > action.yml
          content=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/scriptkidakash81/example/dist/index.js > index.js
          
      - name: Gitleaks
        uses: scriptkidakash81/example/.github/workflows/gitleaks-revanth.yml@main
