name: Gitleaks

# Run workflow each time code is pushed to your repository.
on:
  pull_request:
    branches:
      - main
jobs:

 gitleaks-run:
  uses: scriptkidakash81/example/.github/workflows/gitleaks-revanth.yml@main
  secrets: inherit
