name: Gosec scan

permissions:
  contents: read        # Allows access to the repository contentsa
  actions: write        # Needed for uploading SARIF results
  security-events: write # Allows posting security alerts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.17.0  # Pin to a stable release
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'

      - name: Upload GoSec results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.sarif

      - name: Convert SARIF to JSON
        run: |
          cp results.sarif results.json
 
      - name: Upload GoSec results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.json
