name: Gosec scan

permissions:
  contents: read        # Allows access to the repository contents
  actions: write        # Needed for uploading SARIF results
  security-events: write # Allows posting security alerts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.17.0  # Pin to a stable release
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'

      - name: Check if results.sarif exists
        run: |
          if [ ! -f results.sarif ]; then
            echo "results.sarif not found!"
            exit 1
          fi

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Fail if high or critical vulnerabilities are found
        run: |
          # Check if there are any high or critical vulnerabilities in the SARIF file
          high_critical_vulns=$(jq '[.runs[].results[] | select(.level == "critical")] | length' results.sarif)
          if [ "$high_critical_vulns" -gt 0 ]; then
            echo "High or critical vulnerabilities found! Failing the job."
            exit 1
          fi
        
