name: Semgrep Scan

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/checkout@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep
        
      - name: Run Semgrep
        run: |
          semgrep --config=auto --severity='ERROR' --sarif --sarif-output=semgrep-results.sarif
          
      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results.sarif
          path: semgrep-results.sarif
      - name: Fail if error/critical vulnerabilities found
        run: |
          if grep -q '"level": "high"' semgrep-results.sarif; then
            echo "Error or critical vulnerabilities found. Merge blocked."
            exit 1
          else
            echo "Semgrep scan passed."
          fi
